#!/usr/bin/env bash
# repos-index.sh — Catalog every local repo's graphify graph for AI agents.
#
# The catalog is the point: nothing else tells an agent that other repos' graphs
# exist or where they are, so a question about another repo becomes
# `graphify query "<q>" --graph <path> --budget 800` instead of a filesystem crawl.
#
# The refresh is a safety net. stow/git/.githooks/post-commit already runs
# `graphify update` after every commit in every repo, so graphs are normally
# current; this catches repos not committed to since the hook landed. Pass
# --no-update to skip it and only rewrite the catalog.
#
# Only repos that already have a graphify-out/ are refreshed — `graphify update`
# is AST-only and needs no LLM, while a first build does. Repos without a graph
# are listed, not built; building one is a deliberate choice.
#
# Safe to run from cron. Never run it from inside an agent turn.

set -u
set -o pipefail

REPOS_DIR="${REPOS_DIR:-$HOME/repos}"
CLAUDE_LOCAL="${CLAUDE_LOCAL:-$HOME/.claude/local}"
OUTPUT="$CLAUDE_LOCAL/code-index.md"

DO_UPDATE=1
for arg in "$@"; do
  case "$arg" in
    --no-update) DO_UPDATE=0 ;;
    -h|--help)   sed -n '2,17p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *)           printf 'unknown option: %s\n' "$arg" >&2; exit 2 ;;
  esac
done

if [[ -t 1 ]]; then
  C_RESET=$'\033[0m'; C_GREEN=$'\033[32m'; C_YELLOW=$'\033[33m'; C_CYAN=$'\033[36m'
else
  C_RESET=""; C_GREEN=""; C_YELLOW=""; C_CYAN=""
fi

log_ok()   { printf '%s\n' "  ${C_GREEN}✔ $*${C_RESET}"; }
log_warn() { printf '%s\n' "  ${C_YELLOW}⚠ $*${C_RESET}"; }
log_skip() { printf '%s\n' "  ${C_YELLOW}⊘ $*${C_RESET}"; }
log_info() { printf '%s\n' "  ${C_CYAN}• $*${C_RESET}"; }

if [[ ! -d "$REPOS_DIR" ]]; then
  log_warn "REPOS_DIR not found: $REPOS_DIR — skipping index"
  exit 0
fi

if ! command -v graphify >/dev/null 2>&1; then
  log_warn "graphify not on PATH — skipping index"
  log_info "Install it with: graphify install --platform claude"
  exit 0
fi

printf '▶ Indexing repos in %s\n' "$REPOS_DIR"

mkdir -p "$CLAUDE_LOCAL"

rows=""
missing=""
indexed=0

_node_count() {
  local graph="$1"
  if command -v jq >/dev/null 2>&1; then
    jq -r '.nodes | length' "$graph" 2>/dev/null || printf '?'
  else
    printf '?'
  fi
}

while IFS= read -r gitdir; do
  repo="$(dirname "$gitdir")"
  slug="${repo#"$REPOS_DIR"/}"
  graph="$repo/graphify-out/graph.json"

  if [[ ! -f "$graph" ]]; then
    log_skip "$slug (no graph — run: graphify \"$repo\")"
    missing+="$slug"$'\n'
    continue
  fi

  if (( DO_UPDATE )); then
    log_info "Updating $slug ..."
    if graphify update "$repo" >/dev/null 2>&1; then
      log_ok "$slug"
    else
      log_warn "$slug — update failed, cataloguing the existing graph"
    fi
  else
    log_ok "$slug"
  fi

  nodes="$(_node_count "$graph")"
  updated="$(date -r "$graph" +%Y-%m-%d 2>/dev/null || printf 'unknown')"
  rows+="| \`$slug\` | \`$graph\` | $nodes | $updated |"$'\n'
  indexed=$((indexed + 1))
done < <(find "$REPOS_DIR" -mindepth 2 -maxdepth 4 -type d -name .git 2>/dev/null | sort)

{
  printf '# Code index\n\n'
  printf 'Generated by `repos-index.sh` on %s. Do not edit by hand.\n\n' "$(date +%Y-%m-%d\ %H:%M)"
  printf 'Query a repository instead of grepping it. The traversal is an algorithm, not a\n'
  printf 'model call, and `--budget` caps the output:\n\n'
  printf '```bash\n'
  printf 'graphify query "<question>" --graph <graph path> --budget 800\n'
  printf 'graphify affected "<symbol>" --graph <graph path> --depth 2\n'
  printf 'graphify god-nodes --graph <graph path> --top 10\n'
  printf '```\n\n'
  printf '| Repository | Graph | Nodes | Updated |\n'
  printf '| --- | --- | --- | --- |\n'
  printf '%s' "$rows"
  if [[ -n "$missing" ]]; then
    printf '\n## Not indexed\n\n'
    printf 'No `graphify-out/` yet. A first build is not free — it runs semantic extraction.\n'
    printf 'Build one deliberately with `graphify <path>`.\n\n'
    while IFS= read -r m; do
      [[ -z "$m" ]] && continue
      printf -- '- `%s`\n' "$m"
    done <<< "$missing"
  fi
} > "$OUTPUT"

echo ""
log_ok "Indexed $indexed repo(s) → $OUTPUT"
